<?php
/**
 * Created by Claudio Campos.
 * User: callcocam@gmail.com
 * https://www.sigasmart.com.br
 */
namespace App\Http\Controllers\API;

use App\Category;
use App\Http\Requests\CategoryRequest;

class CategoryController extends AbstractController
{

    protected $model = Category::class;


    public function store(CategoryRequest $request)
    {
        return parent::save($request); // TODO: Change the autogenerated stub
    }
}
