<?php
/**
 * Created by Claudio Campos.
 * User: callcocam@gmail.com
 * https://www.sigasmart.com.br
 */
namespace App\Http\Controllers\API;


use App\Http\Requests\PermissionRequest;
use App\Suports\Shinobi\Models\Role;

class RoleController extends AbstractController
{

    protected $model = Role::class;

    public function store(PermissionRequest $request)
    {
        return parent::save($request); // TODO: Change the autogenerated stub
    }
}
